version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/express-aws
  - source: /res/etc/nginx/conf.d
    destination: /etc/nginx/conf.d
  - source: /res/etc/nginx/default.d
    destination: /etc/nginx
  - source: /res/etc/nginx/nginx.conf
    destination: /etc/nginx/
  - source: /res/etc/systemd/system/express-aws.service
    destination: /etc/systemd/system/

file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/change_permissions
      timeout: 300
      runas: root
    - location: scripts/refresh_nginx
      timeout: 300
      runas: root
    - location: scripts/write_env
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
