version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/express-aws
  - source: /res/etc/nginx/conf.d/express-aws.conf
    destination: /etc/nginx/conf.d/
  - source: /res/etc/nginx/conf.d/helloworld.conf
    destination: /etc/nginx/conf.d/
  - source: /res/etc/nginx/conf.d/php-fpm.conf
    destination: /etc/nginx/conf.d/
  - source: /res/etc/nginx/conf.d/wordpress.conf
    destination: /etc/nginx/conf.d/
  - source: /res/etc/nginx/conf.d/x_forwarded_proto_https.conf
    destination: /etc/nginx/conf.d/
  - source: /res/etc/nginx/default.d/php.conf
    destination: /etc/nginx/default.d/
  - source: /res/etc/nginx/nginx.conf
    destination: /etc/nginx/
  - source: /res/etc/systemd/system/express-aws.service
    destination: /etc/systemd/system/

file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/change_permissions
      timeout: 300
      runas: root
    - location: scripts/install_application
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

