version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing dependencies...
      - npm ci

  build:
    commands:
      - echo Building the TypeScript project...
      - npm run build

  post_build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - '**/*'