#!/bin/bash

REPO=/var/www/express-aws

#qui ci vengono installati i pacchetti necessari per il funzionamento dell'applicazione

function install_app_packages {
    amazon-linux-extras install -y nginx1
    curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -
    yum install -y nodejs
}


function install_resources {

	for f in $REPO/res/*; do
		rsync -avr $f /
	done

	chown -R nginx:nginx $REPO
}


install_app_packages
install_resources
