#!/bin/bash

REPO=/var/www/express-aws

#qui ci vengono installati i pacchetti necessari per il funzionamento dell'applicazione


function install_resources {

	for f in $REPO/res/*; do
		rsync -avr $f /
	done

	chown -R nginx:nginx $REPO
}


# install_app_packages
install_resources
