name: Cloudformation delete
on:
  delete:
    branches:
      - "*"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-oidc-session
          aws-region: eu-north-1

      - name: valerio-cfn-ecs
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: valerio-cfn-ecs
          template: cloudformation/ecs.yml
          command: delete

      - name: valerio-cfn-vpc
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: valerio-cfn-vpc
          template: cloudformation/vpc.yml
          command: delete
